USE [master]
GO

/****** Object:  Database [IISLogging]    Script Date: 11/12/2015 4:27:14 PM ******/
CREATE DATABASE [IISLogging] ON  PRIMARY 
( NAME = N'IISLogging', FILENAME = N'D:\MSData\IISLogging.mdf' , SIZE = 279552KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'IISLogging_log', FILENAME = N'D:\MSLogs\IISLogging_log.ldf' , SIZE = 20480KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [IISLogging] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [IISLogging].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [IISLogging] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [IISLogging] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [IISLogging] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [IISLogging] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [IISLogging] SET ARITHABORT OFF 
GO

ALTER DATABASE [IISLogging] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [IISLogging] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [IISLogging] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [IISLogging] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [IISLogging] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [IISLogging] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [IISLogging] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [IISLogging] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [IISLogging] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [IISLogging] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [IISLogging] SET  DISABLE_BROKER 
GO

ALTER DATABASE [IISLogging] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [IISLogging] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [IISLogging] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [IISLogging] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [IISLogging] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [IISLogging] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [IISLogging] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [IISLogging] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [IISLogging] SET  MULTI_USER 
GO

ALTER DATABASE [IISLogging] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [IISLogging] SET DB_CHAINING OFF 
GO

ALTER DATABASE [IISLogging] SET  READ_WRITE 
GO

USE [master]
GO
CREATE LOGIN [IISParsingUser] WITH PASSWORD=N'PASSWORDGOESHERE' MUST_CHANGE, DEFAULT_DATABASE=[master], CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO
USE [IISLogging]
GO
CREATE USER [IISParsingUser] FOR LOGIN [IISParsingUser]
GO

USE [IISLogging]
GO
CREATE ROLE [db_newtablewritetest] AUTHORIZATION [db_owner]
GO
USE [IISLogging]
GO
EXEC sp_addrolemember N'db_newtablewrite', N'IISParsingUser'
GO
use [IISLogging]
GO
GRANT CREATE TABLE TO [db_newtablewritetest]
GO
